[package]
name = "calc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "^1.0"

[dev-dependencies]
assert_matches = "1.5.0"
cucumber = "0.21"
tokio = { version = "1", features = ["full"] }
futures = "0.3"

[[test]]
name = "calculator"
harness = false

[[test]]
name = "parser"
harness = false

[[test]]
name = "interpreter"
harness = false
